# Workflow for updating the documentation website
---
name: Update Documentation

# Documentation updates can happen in different ways; allow only one at a time
concurrency: release

on:
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Update-Documentation:
    name: Update the documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: true

      - name: Install local website package
        working-directory: ./site
        run: npm ci

      - name: Build documentation website
        working-directory: ./site
        run: npm run build

      - name: Deploy documentation website
        working-directory: ./site
        env:
          GIT_USER: 'phylum-bot'
          GIT_PASS: ${{ secrets.GH_RELEASE_PAT }}
          GIT_USER_NAME: 'phylum-bot'
          GIT_USER_EMAIL: '69485888+phylum-bot@users.noreply.github.com'
        run: npm run deploy
