---
name: Sync `docs` directory to ReadMe

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  Update-Documentation:
    name: Update the documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
       
      - name: Update using rdme
        uses: readmeio/rdme@8.1.1
        with:
          rdme: docs ./docs --key=${{ secrets.README_API }} --version=2-latest
